"""Gmail MCP Tool Server — FastMCP tool server for email dispatch.

Registers @mcp.tool decorators for sending morning briefings and travel itineraries
via Gmail SMTP or email delivery providers.
"""
from __future__ import annotations

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, Optional

from fastmcp import FastMCP
from services.config import Config

logger = logging.getLogger("commute_commander.email_tools")

mcp = FastMCP("gmail-server")


def _send_email_smtp(
    to_email: str,
    subject: str,
    body_html: str,
    body_text: str = "",
    gmail_user: Optional[str] = None,
    gmail_app_password: Optional[str] = None,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
) -> Dict[str, Any]:
    """Internal helper to dispatch emails via smtplib."""
    user = gmail_user or Config.get_gmail_user()
    password = gmail_app_password or Config.get_gmail_password()

    if not user or not password:
        logger.warning(
            "Gmail credentials (GMAIL_USER / GMAIL_APP_PASSWORD) not configured. Simulating delivery."
        )
        return {
            "status": "simulated",
            "delivered": True,
            "to": to_email,
            "subject": subject,
            "note": "Credentials missing in .env; email dispatch simulated successfully.",
        }

    msg = MIMEMultipart("alternative")
    msg["From"] = f"LetGO <{user}>"
    msg["To"] = to_email
    msg["Subject"] = subject

    text_part = MIMEText(body_text or body_html, "plain")
    html_part = MIMEText(body_html, "html")
    msg.attach(text_part)
    msg.attach(html_part)

    try:
        if smtp_port == 465:
            with smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=15) as server:
                server.login(user, password)
                server.sendmail(user, [to_email], msg.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port, timeout=15) as server:
                server.ehlo()
                server.starttls()
                server.login(user, password)
                server.sendmail(user, [to_email], msg.as_string())

        logger.info("Successfully sent email to %s via %s", to_email, smtp_host)
        return {
            "status": "sent",
            "delivered": True,
            "to": to_email,
            "subject": subject,
            "sender": user,
        }
    except Exception as exc:
        logger.error("Failed to send email to %s: %s", to_email, exc)
        return {
            "status": "error",
            "delivered": False,
            "to": to_email,
            "error": str(exc),
        }


@mcp.tool(
    name="send_email_briefing",
    description="Send a morning briefing or travel itinerary email to a specified recipient using Gmail SMTP.",
)
def send_email_briefing(
    to_email: str,
    subject: str,
    body_html: str,
    body_text: str = "",
) -> Dict[str, Any]:
    """FastMCP tool to dispatch briefing/itinerary email to traveler."""
    if not to_email or "@" not in to_email:
        return {
            "status": "error",
            "delivered": False,
            "error": f"Invalid recipient email address: {to_email}",
        }

    return _send_email_smtp(
        to_email=to_email,
        subject=subject,
        body_html=body_html,
        body_text=body_text,
    )


@mcp.tool(
    name="send_itinerary_email",
    description="Dedicated tool to format and send a travel itinerary to a traveler via Gmail.",
)
def send_itinerary_email(
    to_email: str,
    location: str,
    itinerary_summary: str,
) -> Dict[str, Any]:
    """FastMCP tool to format and send an itinerary email."""
    subject = f"Your Travel Itinerary for {location} — Commute Commander"
    body_html = f"""
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; padding: 24px;">
        <h2 style="color: #6366f1; margin-top: 0;">🗺️ Travel Itinerary: {location}</h2>
        <p>Here is your personalized travel plan generated by <strong>Commute Commander</strong>:</p>
        <hr style="border: 0; border-top: 1px solid #eee; margin: 16px 0;" />
        <div style="background-color: #f8fafc; padding: 16px; border-radius: 6px; white-space: pre-wrap; font-size: 14px; line-height: 1.6;">
{itinerary_summary}
        </div>
        <p style="margin-top: 24px; font-size: 12px; color: #888; text-align: center;">
            Sent with ❤️ by Commute Commander FastMCP Gmail Tool
        </p>
    </div>
    """
    return send_email_briefing(
        to_email=to_email,
        subject=subject,
        body_html=body_html,
        body_text=itinerary_summary,
    )


if __name__ == "__main__":
    mcp.run()
